# Generated by Django 4.2.28 on 2026-02-04 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên task')),
                ('tcode', models.CharField(blank=True, max_length=20, verbose_name='T-Code SAP')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('watch_folder', models.TextField(help_text='Dòng 1: đường dẫn chính. Dòng 2+: ghi chú định dạng (bắt đầu bằng #)', verbose_name='Đường dẫn thư mục')),
                ('file_pattern', models.TextField(help_text='Dòng 1: tên file mẫu. Dòng 2+: ghi chú định dạng (bắt đầu bằng #)', verbose_name='Tên file / Pattern')),
                ('file_regex', models.CharField(help_text='VD: ^Quotation \\d{2}-\\w{3}-\\d{4}\\.xlsx$', max_length=500, verbose_name='Regex pattern')),
                ('handler_module', models.CharField(default='tasks.handlers.default_handler', help_text='Python path tới hàm xử lý. VD: tasks.handlers.exchange_rate', max_length=200, verbose_name='Module xử lý')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('paused', 'Tạm dừng'), ('error', 'Lỗi')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('auto_enabled', models.BooleanField(default=True, verbose_name='Tự động quét')),
                ('scan_interval', models.IntegerField(default=30, verbose_name='Chu kỳ quét (giây)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Task Config',
                'verbose_name_plural': 'Task Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, verbose_name='File đã xử lý')),
                ('filepath', models.CharField(max_length=1000, verbose_name='Đường dẫn đầy đủ')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('error', 'Lỗi'), ('skipped', 'Bỏ qua')], max_length=20, verbose_name='Kết quả')),
                ('message', models.TextField(blank=True, verbose_name='Chi tiết')),
                ('rows_processed', models.IntegerField(default=0, verbose_name='Số dòng xử lý')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian chạy')),
                ('duration', models.FloatField(default=0, verbose_name='Thời gian (giây)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.taskconfig')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
