# Generated by Django 4.2.28 on 2026-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='filename_template',
            field=models.CharField(blank=True, help_text='VD: Quotation {dd}-{mmm}-{yyyy}.xlsx', max_length=500, verbose_name='Template tên file (tự động)'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='folder_template',
            field=models.CharField(blank=True, help_text='VD: G:\\Accounting\\ACS\\04.EXCHANGE RATE\\FY{yyyy}\\{mm}.{yyyy}\\', max_length=500, verbose_name='Template đường dẫn (tự động)'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='file_pattern',
            field=models.TextField(help_text='Dòng 1: tên file mẫu. Dòng 2 (bắt đầu bằng #): template tự động', verbose_name='Tên file / Pattern'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='watch_folder',
            field=models.TextField(help_text='Dòng 1: đường dẫn mẫu. Dòng 2 (bắt đầu bằng #): template tự động', verbose_name='Đường dẫn thư mục'),
        ),
    ]
