# Generated by Django 4.2.28 on 2026-02-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskconfig_filename_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='notify_emails',
            field=models.TextField(blank=True, help_text='Mỗi email trên 1 dòng. VD:\nadmin@company.com\nuser@company.com', verbose_name='Danh sách email nhận thông báo'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='notify_on_error',
            field=models.BooleanField(default=True, help_text='Tự động gửi email khi task gặp lỗi', verbose_name='Gửi email khi lỗi'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='notify_on_success',
            field=models.BooleanField(default=False, help_text='Gửi email khi task hoàn thành', verbose_name='Gửi email khi thành công'),
        ),
    ]
