# Generated by Django 4.2.28 on 2026-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskconfig_notify_emails_taskconfig_notify_on_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='last_scheduled_run',
            field=models.DateField(blank=True, help_text='Dùng để tránh chạy trùng trong ngày', null=True, verbose_name='Ngày chạy gần nhất (scheduled)'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='schedule_mode',
            field=models.CharField(choices=[('interval', 'Quét theo chu kỳ (interval)'), ('daily', 'Chạy hàng ngày (đúng giờ)'), ('weekly', 'Chạy hàng tuần')], default='interval', help_text='interval = quét liên tục theo chu kỳ, daily = chạy đúng giờ mỗi ngày', max_length=20, verbose_name='Chế độ lập lịch'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='scheduled_days',
            field=models.CharField(blank=True, default='1,2,3,4,5', help_text='Áp dụng khi chế độ = weekly. VD: 1,2,3,4,5 (Thứ 2-6). 0=CN, 1=T2, ..., 6=T7', max_length=50, verbose_name='Ngày chạy trong tuần'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Áp dụng khi chế độ = daily hoặc weekly. VD: 08:00', null=True, verbose_name='Giờ chạy'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='scan_interval',
            field=models.IntegerField(default=30, help_text='Áp dụng khi chế độ = interval', verbose_name='Chu kỳ quét (giây)'),
        ),
    ]
