# Generated by Django 4.2.28 on 2026-02-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskconfig_last_scheduled_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='param1',
            field=models.TextField(blank=True, help_text='Ghi chú tham số bổ sung cho handler (optional)', null=True, verbose_name='Tham số 1'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='param2',
            field=models.TextField(blank=True, help_text='Ghi chú tham số bổ sung cho handler (optional)', null=True, verbose_name='Tham số 2'),
        ),
    ]
