# Generated by Django 4.2.28 on 2026-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskconfig_param1_taskconfig_param2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskconfig',
            options={'ordering': ['module', '-created_at'], 'verbose_name': 'Task Config', 'verbose_name_plural': 'Task Configs'},
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='module',
            field=models.CharField(choices=[('MM', 'MM - Material Management'), ('PP', 'PP - Production Planning'), ('FICO', 'FICO - Finance & Controlling'), ('SD', 'SD - Sales & Distribution'), ('QM', 'QM - Quality Management'), ('WM', 'WM - Warehouse Management'), ('HR', 'HR - Human Resources'), ('BASIS', 'BASIS - System Admin'), ('OTHER', 'Khác')], default='OTHER', help_text='Phân loại theo module SAP', max_length=20, verbose_name='Module SAP'),
        ),
    ]
