# Generated by Django 4.2.28 on 2026-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskconfig_options_taskconfig_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username từ chương trình mẹ', max_length=100, unique=True, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Tên hiển thị')),
                ('is_admin', models.BooleanField(default=False, help_text='Cho phép truy cập trang Admin để quản lý task và phân quyền', verbose_name='Quyền Admin')),
                ('modules', models.CharField(blank=True, help_text='VD: MM,PP,FICO. Để trống = không có quyền. Nhập * = tất cả', max_length=500, verbose_name='Modules được phép')),
                ('tasks', models.CharField(blank=True, help_text='VD: 1,5,10. Để trống = theo module', max_length=500, verbose_name='Task IDs được phép')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Được sửa')),
                ('can_run', models.BooleanField(default=True, verbose_name='Được chạy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
            },
        ),
        migrations.AddField(
            model_name='tasklog',
            name='executed_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người chạy'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='file_pattern',
            field=models.TextField(verbose_name='Tên file / Pattern'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='file_regex',
            field=models.CharField(max_length=500, verbose_name='Regex pattern'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='filename_template',
            field=models.CharField(blank=True, max_length=500, verbose_name='Template tên file'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='folder_template',
            field=models.CharField(blank=True, max_length=500, verbose_name='Template đường dẫn'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='handler_module',
            field=models.CharField(default='tasks.handlers.default_handler', max_length=200, verbose_name='Module xử lý'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='last_scheduled_run',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày chạy gần nhất'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='module',
            field=models.CharField(choices=[('MM', 'MM - Material Management'), ('PP', 'PP - Production Planning'), ('FICO', 'FICO - Finance & Controlling'), ('SD', 'SD - Sales & Distribution'), ('QM', 'QM - Quality Management'), ('WM', 'WM - Warehouse Management'), ('HR', 'HR - Human Resources'), ('BASIS', 'BASIS - System Admin'), ('OTHER', 'Khác')], default='OTHER', max_length=20, verbose_name='Module SAP'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='notify_emails',
            field=models.TextField(blank=True, verbose_name='Danh sách email'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='notify_on_error',
            field=models.BooleanField(default=True, verbose_name='Gửi email khi lỗi'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='notify_on_success',
            field=models.BooleanField(default=False, verbose_name='Gửi email khi thành công'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='param1',
            field=models.TextField(blank=True, null=True, verbose_name='Tham số 1'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='param2',
            field=models.TextField(blank=True, null=True, verbose_name='Tham số 2'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='scan_interval',
            field=models.IntegerField(default=30, verbose_name='Chu kỳ quét (giây)'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='schedule_mode',
            field=models.CharField(choices=[('interval', 'Quét theo chu kỳ'), ('daily', 'Chạy hàng ngày'), ('weekly', 'Chạy hàng tuần')], default='interval', max_length=20, verbose_name='Chế độ lập lịch'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='scheduled_days',
            field=models.CharField(blank=True, default='1,2,3,4,5', max_length=50, verbose_name='Ngày chạy trong tuần'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ chạy'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='watch_folder',
            field=models.TextField(verbose_name='Đường dẫn thư mục'),
        ),
    ]
