# Generated by Django 5.2.11 on 2026-02-25 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userpermission_tasklog_executed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskconfig',
            options={'ordering': ['module', 'name'], 'verbose_name': 'Task Config', 'verbose_name_plural': 'Task Configs'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='taskconfig',
            name='scan_interval',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='can_run',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='auto_enabled',
            field=models.BooleanField(default=True, verbose_name='Bật auto scan'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='file_pattern',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pattern tên file'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='file_regex',
            field=models.CharField(blank=True, max_length=300, verbose_name='Regex match file'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='filename_template',
            field=models.CharField(blank=True, help_text='VD: Report_{dd}-{mmm}-{yyyy}.xlsx', max_length=300, verbose_name='Template tên file'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='folder_template',
            field=models.CharField(blank=True, help_text='VD: G:\\Data\\FY{yyyy}\\{mm}.{yyyy}\\ - Placeholder: {yyyy} {yy} {mm} {dd} {mmm} {FY}', max_length=500, verbose_name='Template đường dẫn'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='handler_module',
            field=models.CharField(default='tasks.handlers.default_handler', max_length=200, verbose_name='Handler module'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='last_scheduled_run',
            field=models.DateField(blank=True, null=True, verbose_name='Lần chạy scheduled cuối'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='module',
            field=models.CharField(choices=[('MM', 'Material Management'), ('PP', 'Production Planning'), ('FICO', 'Finance & Controlling'), ('SD', 'Sales & Distribution'), ('QM', 'Quality Management'), ('WM', 'Warehouse Management'), ('HR', 'Human Resources'), ('BASIS', 'Basis/Admin'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Module SAP'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='notify_emails',
            field=models.TextField(blank=True, help_text='Mỗi email 1 dòng', verbose_name='Email nhận thông báo'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='notify_on_error',
            field=models.BooleanField(default=False, verbose_name='Gửi mail khi lỗi'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='notify_on_success',
            field=models.BooleanField(default=False, verbose_name='Gửi mail khi thành công'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='param1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tham số 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='param2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tham số 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='schedule_mode',
            field=models.CharField(choices=[('interval', 'Liên tục (theo interval)'), ('daily', 'Hàng ngày (1 lần/ngày)'), ('weekly', 'Hàng tuần')], default='interval', max_length=20, verbose_name='Chế độ lịch'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='scheduled_days',
            field=models.CharField(blank=True, help_text='0-6 (T2-CN), VD: 0,1,2,3,4', max_length=50, verbose_name='Ngày chạy'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Cho daily/weekly', null=True, verbose_name='Giờ chạy'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('paused', 'Tạm dừng')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='watch_folder',
            field=models.CharField(blank=True, max_length=500, verbose_name='Thư mục theo dõi'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='duration',
            field=models.FloatField(default=0, verbose_name='Thời gian (s)'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='executed_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='filename',
            field=models.CharField(max_length=300, verbose_name='Tên file'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='filepath',
            field=models.CharField(max_length=500, verbose_name='Đường dẫn đầy đủ'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='message',
            field=models.TextField(blank=True, verbose_name='Thông báo'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[('success', 'Thành công'), ('error', 'Lỗi'), ('skipped', 'Bỏ qua')], max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Cho phép truy cập trang Admin', verbose_name='Quyền Admin'),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('MM', 'Material Management'), ('PP', 'Production Planning'), ('FICO', 'Finance & Controlling'), ('SD', 'Sales & Distribution'), ('QM', 'Quality Management'), ('WM', 'Warehouse Management'), ('HR', 'Human Resources'), ('BASIS', 'Basis/Admin'), ('OTHER', 'Other')], max_length=20, verbose_name='Module')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Được sửa')),
                ('can_run', models.BooleanField(default=True, verbose_name='Được chạy')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Được xóa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='tasks.userpermission')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Được sửa')),
                ('can_run', models.BooleanField(default=True, verbose_name='Được chạy')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Được xóa')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='tasks.taskconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_permissions', to='tasks.userpermission')),
            ],
            options={
                'verbose_name': 'Task Permission',
                'verbose_name_plural': 'Task Permissions',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
