# Generated by Django 5.2.11 on 2026-02-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermission',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Được xem'),
        ),
        migrations.AddField(
            model_name='taskpermission',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Được xem'),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('MM', 'MM - Material Management'), ('PP', 'PP - Production Planning'), ('FICO', 'FICO - Finance & Controlling'), ('SD', 'SD - Sales & Distribution'), ('QM', 'QM - Quality Management'), ('WM', 'WM - Warehouse Management'), ('HR', 'HR - Human Resources'), ('BASIS', 'BASIS - Basis/Admin'), ('OTHER', 'OTHER - Other')], max_length=20, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='module',
            field=models.CharField(choices=[('MM', 'MM - Material Management'), ('PP', 'PP - Production Planning'), ('FICO', 'FICO - Finance & Controlling'), ('SD', 'SD - Sales & Distribution'), ('QM', 'QM - Quality Management'), ('WM', 'WM - Warehouse Management'), ('HR', 'HR - Human Resources'), ('BASIS', 'BASIS - Basis/Admin'), ('OTHER', 'OTHER - Other')], default='OTHER', max_length=20, verbose_name='Module SAP'),
        ),
    ]
