# Generated by Django 5.2.11 on 2026-02-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_modulepermission_can_view_taskpermission_can_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(help_text='SAP Client (VD: 100, 200)', max_length=10, verbose_name='Client')),
                ('username', models.CharField(max_length=50, verbose_name='User SAP')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAP User',
                'verbose_name_plural': 'SAP Users',
                'unique_together': {('client', 'username')},
            },
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='sap_user',
            field=models.ForeignKey(blank=True, help_text='User SAP để chạy task này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.sapuser', verbose_name='SAP User'),
        ),
    ]
