# Generated by Django 5.2.11 on 2026-03-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_sapuser_taskconfig_sap_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhóm người dùng',
                'verbose_name_plural': 'Nhóm người dùng',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='auto_enabled',
            field=models.BooleanField(default=False, verbose_name='Bật auto scan'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='tasks.usergroup', verbose_name='Nhóm'),
        ),
        migrations.CreateModel(
            name='GroupTaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Được xem')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Được sửa')),
                ('can_run', models.BooleanField(default=True, verbose_name='Được chạy')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Được xóa')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='tasks.taskconfig')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_permissions', to='tasks.usergroup')),
            ],
            options={
                'verbose_name': 'Group Task Permission',
                'verbose_name_plural': 'Group Task Permissions',
                'unique_together': {('group', 'task')},
            },
        ),
        migrations.CreateModel(
            name='GroupModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('MM', 'MM - Material Management'), ('PP', 'PP - Production Planning'), ('FICO', 'FICO - Finance & Controlling'), ('SD', 'SD - Sales & Distribution'), ('QM', 'QM - Quality Management'), ('WM', 'WM - Warehouse Management'), ('HR', 'HR - Human Resources'), ('BASIS', 'BASIS - Basis/Admin'), ('OTHER', 'OTHER - Other')], max_length=20, verbose_name='Module')),
                ('can_view', models.BooleanField(default=True, verbose_name='Được xem')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Được sửa')),
                ('can_run', models.BooleanField(default=True, verbose_name='Được chạy')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Được xóa')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='tasks.usergroup')),
            ],
            options={
                'verbose_name': 'Group Module Permission',
                'verbose_name_plural': 'Group Module Permissions',
                'unique_together': {('group', 'module')},
            },
        ),
    ]
