# Generated by Django 5.2.11 on 2026-04-06 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_usergroup_alter_taskconfig_auto_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='sap_password',
            field=models.CharField(blank=True, help_text='Mật khẩu SAP của user này, dùng khi chạy task thủ công. Khác với mật khẩu của SAPUser (dùng cho auto run).', max_length=200, verbose_name='Mật khẩu SAP'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='sap_user',
            field=models.ForeignKey(blank=True, help_text='User SAP để chạy task này (dùng cho auto run)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.sapuser', verbose_name='SAP User'),
        ),
    ]
