# Generated by Django 5.2.11 on 2026-04-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_userpermission_sap_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='sample_file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn file mẫu'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[('success', 'Thành công'), ('partial', 'Có dòng lỗi'), ('error', 'Lỗi'), ('skipped', 'Bỏ qua')], max_length=20, verbose_name='Trạng thái'),
        ),
    ]
